version: '3'
services:
  nginx: # should be equal to the name of the folder name this compose is in
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/js:/etc/nginx/inc/js:ro
    # the name of the folder on the host needs to have the name 'data' and it should contain the files you want to persist between docker container builds.
    - ./data/nginx:/etc/nginx/conf.d:ro
    - ./data/logs/nginx:/var/log/nginx/:ro
    - ./data/certbot/conf:/etc/letsencrypt:ro
    - ./data/certbot/www:/var/www/certbot:ro
    - ./data/maps:/var/www/maps:ro
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done
      & nginx -g "daemon off;"'
    restart: unless-stopped
networks: # this needs to be added as we spin off a default network 'trufi-server' to connect this module to the reverse proxy nginx
  default:
    name: trufi-server
