version: '3'
services:
  nginx:
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/js:/etc/nginx/inc/js:ro
    - ./data/nginx:/etc/nginx/conf.d:ro
    - ./data/logs/nginx:/var/log/nginx/:ro
    - ./data/certbot/conf:/etc/letsencrypt:ro
    - ./data/certbot/www:/var/www/certbot:ro
    - ./data/maps:/var/www/maps:ro
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done
      & nginx -g "daemon off;"'
    restart: unless-stopped
networks:
  default:
    name: trufi-server
